name: jtasks
description: JTasks is a cross-platform tasks management software that can assist you manage tasks and progress of your job or project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  objectbox: ^1.7.0
  flex_color_scheme: ^6.1.2
  google_fonts: ^3.0.1
  flutter_admin_scaffold: ^1.1.2
  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/google_fonts/

